# Generated by Django 5.1.2 on 2024-10-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_fundacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('transmision', models.CharField(choices=[('Manual', 'Manual'), ('Automática', 'Automática')], max_length=50)),
                ('combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('Híbrido', 'Híbrido')], max_length=50)),
                ('traccion', models.CharField(choices=[('Delantera', 'Delantera'), ('Trasera', 'Trasera'), ('Integral', 'Integral')], max_length=50)),
                ('numero_puertas', models.PositiveIntegerField(choices=[(2, 2), (4, 4), (5, 5)], default=4)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modelo', models.CharField(max_length=100)),
                ('categoria', models.ManyToManyField(to='appOutletCar.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.marca')),
            ],
        ),
    ]
