# Generated by Django 5.1.2 on 2024-10-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='anio',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='coche',
            name='color',
            field=models.CharField(default='Blanco', max_length=50),
        ),
        migrations.AlterField(
            model_name='coche',
            name='kilometraje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coche',
            name='traccion',
            field=models.CharField(choices=[('Delantera', 'Delantera'), ('Trasera', 'Trasera'), ('Total', 'Total')], max_length=50),
        ),
    ]
