# Generated by Django 4.2.16 on 2024-10-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0002_alter_coche_anio_alter_coche_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='descapotable',
            field=models.BooleanField(default=False),
        ),
    ]
