# Generated by Django 5.1.3 on 2024-12-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0004_coche_imagen_marca_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/coches', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/marcas', verbose_name='Image'),
        ),
    ]
