# Generated by Django 5.1.3 on 2024-12-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0005_alter_coche_imagen_alter_marca_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coche',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
