# Generated by Django 5.1.3 on 2024-12-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0006_rename_categoria_coche_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coche',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
